---
- name: recreate api container
  docker_container:
    name: api
    image: 'tsuru/api:{{ tsuru.version }}'
    log_driver: journald
    state: started
    restart_policy: always
    recreate: yes
    network_mode: host
    volumes:
      - '/etc/tsuru:/etc/tsuru:ro'
