---
- name: get tsurud token
  shell: 'docker exec api tsurud token'
  register: get_tsurud_token

- name: create .bash_profile
  template:
    src: bash_profile.j2
    dest: /home/git/.bash_profile
    owner: git
    group: git
