---
- import_tasks: config.yml
  become: yes
  tags: tsuru_config

- import_tasks: container.yml
  become: yes
  tags: tsuru_container

- import_tasks: ufw.yml
  become: yes
  tags: tsuru_ufw

- import_tasks: git.yml
  become: yes
  tags: tsuru_git

- import_tasks: client.yml
  become: yes
  tags: tsuru_client

- import_tasks: initialize.yml
  become: yes
  tags: tsuru_initialize
