---
- include: config.yml
  become: yes
  tags: tsuru_config

- include: container.yml
  become: yes
  tags: tsuru_container

- include: ufw.yml
  become: yes
  tags: tsuru_ufw

- include: git.yml
  become: yes
  tags: tsuru_git

- include: client.yml
  become: yes
  tags: tsuru_client

- include: initialize.yml
  become: yes
  tags: tsuru_initialize
