---
- name: recreate mongo container
  docker_container:
    name: mongo
    image: mongo
    log_driver: journald
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - '{{ mongo.host }}:{{ mongo.port }}:27017'
    volumes:
      - '/var/lib/mongo:/data/db'
