---
- import_tasks: hostname.yml
  become: yes
  tags: common_hostname

- import_tasks: timezone.yml
  become: yes
  tags: common_timezone

- import_tasks: journald.yml
  become: yes
  tags: common_journald

- import_tasks: apt.yml
  become: yes
  tags: common_apt

- import_tasks: ssh.yml
  become: yes
  tags: common_ssh

- import_tasks: ufw.yml
  become: yes
  tags: common_ufw

- import_tasks: storage.yml
  become: yes
  tags: common_storage
