---
- name: create docker group
  group:
    name: docker

- name: add you to docker group
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: yes
  when: ansible_env.USER != 'root'
