---
- include: prerequisites.yml
  become: yes
  tags: docker_prerequisites

- include: install.yml
  become: yes
  tags: docker_install

- include: config.yml
  become: yes
  tags: docker_config

- include: python.yml
  become: yes
  tags: docker_python

- include: group.yml
  become: yes
  tags: docker_group
