---
- import_tasks: prerequisites.yml
  become: yes
  tags: docker_prerequisites

- import_tasks: install.yml
  become: yes
  tags: docker_install

- import_tasks: config.yml
  become: yes
  tags: docker_config

- import_tasks: python.yml
  become: yes
  tags: docker_python

- import_tasks: group.yml
  become: yes
  tags: docker_group
