---
- name: recreate registry container
  docker_container:
    name: registry
    image: 'registry:2'
    log_driver: journald
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - '{{ docker_registry.host }}:{{ docker_registry.port }}:5000'
    volumes:
      - '/mnt/data/registry:/var/lib/registry'
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
