---
- name: check letsencrypt directory
  stat:
    path: '/etc/letsencrypt/live/{{ ansible_nodename }}'
  register: check_letsencrypt_directory

- name: create letsencrypt certification
  shell: >
    docker run --log-driver journald \
               --name letsencrypt_certonly \
               -p {{ letsencrypt.port }}:{{ letsencrypt.port }} \
               --rm \
               -v /etc/letsencrypt:/etc/letsencrypt \
               -v /var/lib/letsencrypt:/var/lib/letsencrypt \
               -v /var/log/letsencrypt:/var/log/letsencrypt \
               certbot/certbot \
               certonly -d {{ ansible_nodename }} --standalone -n --agree-tos -m {{ letsencrypt.email }}
  when: not check_letsencrypt_directory.stat.exists
