---
- name: create letsencrypt certification
  docker_container:
    name: letsencrypt
    image: certbot/certbot
    log_driver: journald
    state: started
    cleanup: yes
    detach: no
    command: 'certonly -d {{ ansible_nodename }} --standalone -n --agree-tos -m {{ letsencrypt.email }}'
    ports:
      - '{{ letsencrypt.port }}:{{ letsencrypt.port }}'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/var/lib/letsencrypt:/var/lib/letsencrypt'
      - '/var/log/letsencrypt:/var/log/letsencrypt'
  ignore_errors: yes
