---
- include: config.yml
  become: yes
  tags: letsencrypt_config

- include: ufw.yml
  become: yes
  tags: letsencrypt_ufw

- include: container.yml
  become: yes
  tags: letsencrypt_container

- include: cron.yml
  become: yes
  tags: letsencrypt_cron
