---
- import_tasks: config.yml
  become: yes
  tags: letsencrypt_config

- import_tasks: ufw.yml
  become: yes
  tags: letsencrypt_ufw

- import_tasks: container.yml
  become: yes
  tags: letsencrypt_container
