---
tsuru:
  host: 0.0.0.0
  port: 8080
  version: v1.4.0
  quota:
    units: 1
    apps: 3
  root:
    email: admin@example.com
    password: admin123
  roles:
    - name: team-create
      context: global
      default: no
      permissions: role.update team.create
    - name: team-member
      context: team
      default: team-create
      permissions: app service-instance team
    - name: hackathon-tutor
      context: global
      default: no
      permissions: app.read app.run platform.create platform.read platform.update 
  platforms:
    - buildpack
    - go
    - java
    - nodejs
    - php
    - python
    - ruby
    - static
